# Generated by Django 4.2.1 on 2023-06-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, default='', max_length=180, null=True)),
                ('Empcode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
